language: php

php:
  - 7.3

script:
  - bash psf/tools/lint.sh

notifications:
  irc:
    channels:
      - "irc.tm-irc.org#petan"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} - %{author} %{message} %{build_url}"
