---
- hosts: localhost
  tasks:
      - include_vars: vars.yml
      - uri:
          url: "{{ dns_tool }}/api.php"
          validate_certs: no
          method: POST
          body_format: form-urlencoded
          body:
            action: login
            loginUsername: "{{ dns_tool_username }}"
            loginPassword: "{{ dns_tool_password }}"
        name: 'Login to DNS tool'
        register: login
        failed_when: "login.json.result != 'success'"

      - uri:
          url: "{{ dns_tool }}/api.php"
          validate_certs: no
          method: POST
          body_format: form-urlencoded
          body:
            action: delete_record
            record: "petr.bena.cz.preprod"
            type: A
            value: 1.1.2.2
          headers:
            Cookie: "{{ login.set_cookie }}"
        name: 'Delete record'
        register: this
        failed_when: "this.json.result != 'success'"

      - uri:
          url: "{{ dns_tool }}/api.php"
          validate_certs: no
          method: POST
          body_format: form-urlencoded
          body:
            action: logout
          headers:
            Cookie: "{{ login.set_cookie }}"
        name: 'Logout from DNS tool'
        register: this
        failed_when: "this.json.result != 'success'"
