#!/bin/sh

#version=`git tag | tail -1`
version=`git for-each-ref --sort=creatordate --format '%(refname) %(creatordate)' refs/tags | tail -1 | sed 's/\s.*//' | sed 's/..........//'`

if [ ! -f 'index.php' ]; then
    echo "You have to run this from root folder of project"
    exit 1
fi

if [ -f "/tmp/dnsphpadmin_$version.tar.gz" ];then
    echo "/tmp/dnsphpadmin_$version.tar.gz already exist"
    exit 1
fi
if [ -d "/tmp/dnsphpadmin_$version" ];then
    echo "/tmp/dnsphpadmin_$version already exists"
    exit 1
fi
cp -rp . "/tmp/dnsphpadmin_$version" || exit 1

# Remove stuff we don't need to package
rm -rf "/tmp/dnsphpadmin_$version/.git"
rm -f "/tmp/dnsphpadmin_$version/.gitignore"
rm -f "/tmp/dnsphpadmin_$version/.gitmodules"
rm -rf "/tmp/dnsphpadmin_$version/util"
rm -rf "/tmp/dnsphpadmin_$version/examples"
rm -f "/tmp/dnsphpadmin_$version/.travis.yml"

cd /tmp || exit 1
tar -zcf "/tmp/dnsphpadmin_$version.tar.gz" "dnsphpadmin_$version"
rm -rf "/tmp/dnsphpadmin_$version"
echo "/tmp/dnsphpadmin_$version.tar.gz created"
